### PR TITLE
New OGGM_Edu interface

### PR DESCRIPTION
**Pull request by Holmgren825**
This PR introduce the new version of OGGM_Edu and along with it a new way of interacting with the core of OGGM for educational purposes. The new classes provide the user with objects that are designed to be glacier centric and feel intuitive to use with methods for e.g. progressing the glacier, plotting the state, comparing glaciers etc. All without the user having to know how to write code for oggm,  numpy and matplotlib.

This also includes a **breaking change** for previous use of oggm_edu by moving the old functions into a new namespace `legacy_functions`. Hence any programs relying on these would have to update import statements.

### CODE REVIEW

**Comment by Holmgren825** [comment]
- Maybe time for version bunmp?
- wip notebook should probably be moved/deleted?

**Comment by fmaussion** [comment]
> Maybe time for version bunmp?

Yes I'll do that before merging this.

> wip notebook should probably be moved/deleted?

Yes.

**Comment by Holmgren825** [comment]
> > wip notebook should probably be moved/deleted?
> 
> Yes.
Done.

**Comment by Holmgren825** [comment]
https://github.com/OGGM/oggm-edu-notebooks/pull/56 updates notebooks.

**Comment by fmaussion** [comment]
@Holmgren825 I have just pushed to your branch in https://github.com/OGGM/oggm-edu/pull/133/commits/b8ff5ae806488d9c849798c70bfceebd81429b54 (locally, you'll need to do a `git pull` to update, in the hope that you don't have uncommitted changes).

This is looking really good! I have a few general comments before I continue my review:

- let's try to stick to pep8 regarding attribute names, variable names, modules, etc:
    - Your classes are OK (CamelCase)
    - some attributes need renaming (`self.ELA` -> `self.ela`). I know that it would make sense sometimes (e.g. "ELA") but I think that the most predictable is still to always use the same case (i.e. lower case; upper case means constants in pep8).
    -  some modules need renaming (`glacierBed` -> `glacier_bed`)
- regarding code style, since this is a young project let's [blackify](https://black.readthedocs.io) it. If you don't want to bother with that don't worry I'll do it. 
- It's not recommended  to set global parameters (matplotlib, seaborn) at import. It's a bit more work, but I have now put those settings in a new decorator that you'll have to add to all your plotting methods (I've done it to one as an example). Maybe this will also allow you to remove some duplicated code and put it in the decorator, but it's unlikely.

Let me know if you have any questions! Once this is done I'll continue the review.

**Comment by Holmgren825** [comment]
Thanks! 
- Attributes: agree
- Modules: So glacier_bed, glacier_collection and mass_balance. Will fix.
- Black seems easy enough. Should we go for default black? Noticed that line length is set to 88 char, so not pep8 standard.
- Cool! I've tried to split some of the plotting functionality into components e.g. create a base plot with one method and then extend upon this by other methods. Maybe this can be done even more. Will have to think a little.

**Comment by fmaussion** [comment]
>  Should we go for default black? Noticed that line length is set to 88 char, so not pep8 standard.

Yes, let's keep it "pure black" :wink:. I've tested it yesterday and it looks quite good I think.

**Comment by Holmgren825** [comment]
>     * Attributes: agree
> 
>     * Modules: So glacier_bed, glacier_collection and mass_balance. Will fix.
> 
>     * Black seems easy enough. Should we go for default black? Noticed that line length is set to 88 char, so not pep8 standard.
> 
>     * Cool! I've tried to split some of the plotting functionality into components e.g. create a base plot with one method and then extend upon this by other methods. Maybe this can be done even more. Will have to think a little.

This is now done. Plotting methods could maybe still be further split up into components for extended re-use. But this won't affect the user and notebooks so can be put on hold I think.

**Comment by Holmgren825** [comment]
I couldn't leave it alone so worked some more on the `MassBalance`. Think I have something now that allow the user to customise the mb profile by passing any number of gradients and the altitudes of the breakpoints between them. Allows for the creation of something like this
image
If the resulting profile is reasonable is another question, but not sure if it matters. Alternative is a linear profile after all.

Maybe I'm missing something else that makes this a bad idea.

Will probably push this early next week after some polishing.

**Comment by fmaussion** [comment]
Excellent! Does this also changes the class structure?

> Maybe I'm missing something else that makes this a bad idea.

I wouldn't see why. A very typical use case is the two gradients from the app

> Will probably push this early next week after some polishing.

Thanks! This still gives me more time then, but we HAVE to merge by next week ;-)

**Comment by fmaussion** [comment]
Yes OK, but inheriting from `oggm.MassBalanceModel` makes more sense so that's another good outcome - great!

**Comment by Holmgren825** [comment]
Ok, except for any issues/suggested changes that come up in review, there wont be any more changes added to this pr now.

**Comment by Holmgren825** [comment]
Added new tests and some small bug fixes.

**Pull request merged**
