### PR TITLE
Four new experiments for the simulator

### PR DESCRIPTION
**Pull request by pat-schmitt**
Here I added four new experiments for the simulator. I hope everything is understandable.

For the 'AAR' and 'Balance Ratio' experiment a new version of the simulator must be released, with the possibility for two different Mass-Balance gradients.

### CODE REVIEW

**Comment by fmaussion** [comment]
awesome! 

Should we release the simulator now?

What about https://github.com/OGGM/glacier_simulator/issues/14 ?

**Comment by pat-schmitt** [comment]
Today I also will play around with the loading spinner (https://github.com/OGGM/glacier_simulator/issues/11), so maybe we can wait for this. I will try out different versions and than we can decide which looks best

**Comment by pat-schmitt** [comment]
Ok so maybe we make a version of the simulator as it is and for the next version I will have a look at the templates (which include the loading spinner in their design)

**Comment by pat-schmitt** [comment]
And with Holoviews 1.14.1 also https://github.com/OGGM/glacier_simulator/issues/14 is closed

**Comment by fmaussion** [comment]
OK agreed. I'll tag the simulator version and publish it on our server.

**Comment by fmaussion** [comment]
Thanks a lot! these experiments are awesome!!!

**Pull request merged**
