### PR TITLE
changed docker port from 8080:80 to 8080:8080

### PR DESCRIPTION
**Pull request by pat-schmitt**

### CODE REVIEW

**Comment by fmaussion** [comment]
Is it enough to let the app run?

**Comment by pat-schmitt** [comment]
Yes, with this change the app is running locally on docker again.

**Comment by fmaussion** [comment]
@TimoRoth , could it be the reason why https://bokeh.oggm.org/simulator/app is not working?

**Comment by TimoRoth** [comment]
That page is still not working because of the same crash:

```
2020-04-08 16:28:24: oggm.cfg: Using configuration file: /usr/local/pyenv/versions/3.7.6/lib/python3.7/site-packages/oggm/params.cfg
bokeh.application.application - ERROR - Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f89182fb590>: __init__() got an unexpected keyword argument 'max_dt'
File "flowline.py", line 956, in __init__:
inplace=inplace, **kwargs) Traceback (most recent call last):
  File "/home/bokeh/venv/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/bokeh/app/app.ipynb", line 2963, in <module>
    "    global last_info_text_stage\n",
  File "/home/bokeh/app/app.ipynb", line 1898, in init_model
    "def change_figure_size(arg=None):\n",
  File "/usr/local/pyenv/versions/3.7.6/lib/python3.7/site-packages/oggm/core/flowline.py", line 956, in __init__
    inplace=inplace, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_dt'
```

**Comment by pat-schmitt** [comment]
Ah ok, I got this error also some time ago and excluded the `max_dt` variable in `FlowlineModel = partial(FluxBasedModel, min_dt=0, cfl_number=0.02)`, so with one of the newer commits of the app this error should be away.
@fmaussion you added this together with the change of `cfg.initialize_minimal()`.

**Comment by TimoRoth** [comment]
indeed, updating to the latest version fixes it.

**Pull request merged**
