### PR TITLE
description about how to find the notebooks 

### PR DESCRIPTION
**Pull request by zschirmeister**

### CODE REVIEW

**Comment by fmaussion** [comment]
Great! Should we merge this now and meet some time next week?

**Comment by zschirmeister** [comment]
Of course, we can already merge it. But there are still some things missing.

Zitat von Fabien Maussion <notifications@github.com>:

**Comment by fmaussion** [comment]
OK! Then I'll wait! Ping me with @fmaussion when its ready to review or merge ;-)

**Comment by fmaussion** [comment]
Thanks so much! Merging now

**Pull request merged**
