### PR TITLE
Adding CdeC.py helper module

### PR DESCRIPTION
**Pull request by ehultee**
Created CdeC.py, which should contain helper functions developed for Clubes de Ciencia applications. Notebooks in ehultee/CdeC-glaciologia should be updated to import from this module as well as edu.

First helper function converts ice volume to an equivalent volume of freshwater.

### CODE REVIEW

**Comment by ehultee** [comment]
I only wanted to add the one file, but now it's attached all the commits between my fork and this pull request.  Amateur mistake - you can ignore for now, will try to fix it by Monday.

**Comment by ehultee** [comment]
Update: Tried to form a new branch (cdec) and use cherry-pick to select only the relevant commit, but it appeared empty.  Tried to rebase the new branch and got a fatal error.  Don't know how else to fix this pull request from here.

If you can approve only one of the commits (the last one, hash 48da744c145ec33d27f5c1390f566da867d9adbd) then do that.  If not, please advise how to fix this - I am not skilled enough to do it independently.

**Comment by fmaussion** [comment]
Thanks!

Sorry, I actually meant that this module should be in your repo (https://github.com/ehultee/CdeC-glaciologia) so that importing it from your notebooks works during the test phase - when we'll setup the cluster for your students we'll find a way to make it work regardless where the notebooks are started from (with a simple python package)

**Comment by ehultee** [comment]
Ah yes makes sense.  I'll close this one now and put CdeC.py in the dedicated repo.

**Pull request closed without merging**
